//! Abstract syntax of DLC.
//!
//! The concrete grammar is frozen in `spec/syntax.md`. This module mirrors that
//! BNF in Rust types and is the source from which `lean/DLC/Syntax.lean` is
//! generated by Aeneas.

use alloc::boxed::Box;
use alloc::vec::Vec;

use crate::ifc::Label;
use crate::obligation::Obligation;
use crate::principal::Principal;
use crate::time::TimeBound;

/// Proposition forms — what a proof term proves.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Prop {
    /// ⊤ — trivial proposition.
    Top,
    /// ⊥ — absurdity.
    Bot,
    /// Atomic proposition, identified by index into a global atom table.
    Atom(u32),
    /// φ ⊃ ψ — implication.
    Imp(Box<Prop>, Box<Prop>),
    /// φ ∧ ψ — additive conjunction (non-linear).
    And(Box<Prop>, Box<Prop>),
    /// φ ∨ ψ — additive disjunction.
    Or(Box<Prop>, Box<Prop>),
    /// p says φ — affirmation modality.
    Says(Principal, Box<Prop>),
    /// p ⇒ q — speaks-for relation between principals.
    SpeaksFor(Principal, Principal),
    /// φ @ ℓ — IFC label annotation.
    At(Box<Prop>, Label),
    /// □_O φ — proposition with attached obligation.
    Boxed(Obligation, Box<Prop>),
    /// ◇_τ φ — proposition that must hold within time bound τ.
    Within(TimeBound, Box<Prop>),
    /// φ ⊗ ψ — multiplicative conjunction (linear "must do both").
    Tensor(Box<Prop>, Box<Prop>),
    /// φ ⊸ ψ — linear implication.
    Lolli(Box<Prop>, Box<Prop>),
}

/// Proof term forms — runtime objects whose well-typedness is the calculus.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Term {
    /// Variable reference by de-Bruijn index.
    Var(u32),
    /// Lambda abstraction; the bound variable has the indicated proposition.
    Lam(Box<Prop>, Box<Term>),
    /// Application.
    App(Box<Term>, Box<Term>),
    /// Signed affirmation: `⟨M, σ⟩_p` introducing `p says φ`.
    Sign(Principal, Box<Term>, Signature),
    /// Verification: checks that a signature on a term is valid under p's key.
    Verify(Principal, Box<Term>, Signature),
    /// Delegation: `delegate(M, N)` produces `(p ⊓ q) says φ` from a
    /// speaks-for affirmation and a says-affirmation.
    Delegate(Box<Term>, Box<Term>),
    /// Attenuation: weakens an affirmation along provable implication.
    Attenuate(Box<Term>, Box<Prop>),
    /// Discharge: consumes an obligation to extract the underlying proposition.
    Discharge(Box<Term>, Box<Term>),
    /// IFC label lifting.
    LiftLabel(Label, Box<Term>),
    /// IFC declassification (requires a declassification policy witness).
    Declassify(Label, Box<Term>, Box<Term>),
    /// Time-anchor invocation: proves `now < τ` from a trusted anchor.
    Now(TimeBound),
    /// Within-modality introduction.
    WithinIntro(TimeBound, Box<Term>),
}

/// A cryptographic signature carried by `Sign` and `Verify` terms.
///
/// In the logic, signatures are opaque byte strings; the `verify` judgment of
/// `Γ ⊢_K M : φ` (T2) is what relates them to the keyring `K`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Signature {
    /// Algorithm identifier (e.g. Ed25519 = 0).
    pub alg: u8,
    /// Raw signature bytes (64 for Ed25519).
    pub bytes: Vec<u8>,
}
