//! Abstract syntax of DLC.
//!
//! The concrete grammar is frozen in `spec/syntax.md`. This module mirrors that
//! BNF in Rust types and is the source from which `lean/DLC/Syntax.lean` is
//! generated by Aeneas.

use alloc::boxed::Box;
use alloc::vec::Vec;

use crate::ifc::Label;
use crate::obligation::Obligation;
use crate::principal::Principal;
use crate::time::TimeBound;

/// Proposition forms — what a proof term proves.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Prop {
    /// ⊤ — trivial proposition.
    Top,
    /// ⊥ — absurdity.
    Bot,
    /// Atomic proposition, identified by index into a global atom table.
    Atom(u32),
    /// φ ⊃ ψ — implication.
    Imp(Box<Prop>, Box<Prop>),
    /// φ ∧ ψ — additive conjunction (non-linear).
    And(Box<Prop>, Box<Prop>),
    /// φ ∨ ψ — additive disjunction.
    Or(Box<Prop>, Box<Prop>),
    /// p says φ — affirmation modality.
    Says(Principal, Box<Prop>),
    /// p ⇒ q — speaks-for relation between principals.
    SpeaksFor(Principal, Principal),
    /// φ @ ℓ — IFC label annotation.
    At(Box<Prop>, Label),
    /// □_O φ — proposition with attached obligation.
    Boxed(Obligation, Box<Prop>),
    /// ◇_τ φ — proposition that must hold within time bound τ.
    Within(TimeBound, Box<Prop>),
    /// φ ⊗ ψ — multiplicative conjunction (linear "must do both").
    Tensor(Box<Prop>, Box<Prop>),
    /// φ ⊸ ψ — linear implication.
    Lolli(Box<Prop>, Box<Prop>),
}

/// Proof term forms — runtime objects whose well-typedness is the calculus.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Term {
    /// Variable reference by de-Bruijn index.
    Var(u32),
    /// Lambda abstraction; the bound variable has the indicated proposition.
    Lam(Box<Prop>, Box<Term>),
    /// Application.
    App(Box<Term>, Box<Term>),
    /// Signed affirmation: `⟨M, σ⟩_p` introducing `p says φ`.
    Sign(Principal, Box<Term>, Signature),
    /// Verification: checks that a signature on a term is valid under p's key.
    Verify(Principal, Box<Term>, Signature),
    /// Delegation: `delegate(M, N)` produces `(p ⊓ q) says φ` from a
    /// speaks-for affirmation and a says-affirmation.
    Delegate(Box<Term>, Box<Term>),
    /// Attenuation: weakens an affirmation along provable implication.
    Attenuate(Box<Term>, Box<Prop>),
    /// says-E: `let ⟨x⟩_p = M in N`, written `saysBind_p(M, N)` in
    /// `spec/syntax.md`. BINDS `x:φ` in `N` — a real binder, so `shift` and
    /// `subst` bump the cutoff by one under `N`. The conclusion preserves the
    /// modality (`p says ψ`).
    ///
    /// Added 2026-07-20. The rule existed but concluded at `Term::App`, which
    /// is not a binder, so the cutoff was never bumped for `N` and the says-E
    /// case of any shift/substitution lemma was off by one and unprovable.
    SaysBind(Principal, Box<Term>, Box<Term>),
    /// Obligation attachment: `box_O(M, N)` introducing `□_O φ` from a proof
    /// `M : φ` and obligation evidence `N : O`.
    ///
    /// The obligation is carried by the TERM, not merely by the typing
    /// derivation — the same annotation discipline as `Lam`, `LiftLabel`,
    /// `Declassify` and `WithinIntro`. This is what lets `pending_obligations`
    /// (T4) be a function of syntax alone; recovering `O` from `N`'s type
    /// instead would force T4 to quantify over derivations rather than terms.
    /// See `spec/syntax.md` §5 and `spec/t4-obligation-design-2026-07.md`.
    Boxed(Obligation, Box<Term>, Box<Term>),
    /// Discharge: consumes an obligation to extract the underlying proposition.
    Discharge(Box<Term>, Box<Term>),
    /// IFC label lifting.
    LiftLabel(Label, Box<Term>),
    /// IFC declassification (requires a declassification policy witness).
    Declassify(Label, Box<Term>, Box<Term>),
    /// Time-anchor invocation: proves `now < τ` from a trusted anchor.
    Now(TimeBound),
    /// Within-modality introduction.
    WithinIntro(TimeBound, Box<Term>),

    // --- Additive product (and) ---
    /// `⟨M, N⟩` — additive conjunction introduction (`and-I`).
    Pair(Box<Term>, Box<Term>),
    /// `π₁ M` — left projection (`and-Eₗ`).
    Fst(Box<Term>),
    /// `π₂ M` — right projection (`and-Eᵣ`).
    Snd(Box<Term>),

    // --- Additive coproduct (or) ---
    /// `inl_ψ M` — left injection for `φ ∨ ψ` (`or-I`-left).
    /// The carried proposition is the *other* disjunct (the one we're
    /// declaring not to be the case here); explicit so type inference is
    /// strictly bottom-up.
    Inl(Box<Prop>, Box<Term>),
    /// `inr_φ M` — right injection for `φ ∨ ψ` (`or-I`-right).
    Inr(Box<Prop>, Box<Term>),
    /// `case M of inl x ⇒ N | inr y ⇒ P` — disjunction elimination
    /// (`or-E`). The first branch binds the left disjunct's witness; the
    /// second binds the right's.
    Case(Box<Term>, Box<Term>, Box<Term>),

    // --- Multiplicative product (tensor) ---
    /// `M ⊗ N` — linear tensor introduction (`tensor-I`).
    TensorIntro(Box<Term>, Box<Term>),
    /// `let x⊗y = M in N` — linear tensor elimination (`tensor-E`).
    /// Binds two linear hypotheses simultaneously.
    LetTensor(Box<Term>, Box<Term>),

    // --- Says elimination as an explicit let ---
    /// `let ⟨x⟩_p = M in N` — `says-E` / `says-extract` as an explicit
    /// binder rather than abusing `App`.
    LetSays(Principal, Box<Term>, Box<Term>),
    /// `sfExtract(M)` — `sf-extract`: from `p says (q ⇒ p)` extract
    /// `q ⇒ p`. Trusts the principal's affirmation.
    SfExtract(Box<Term>),
}

/// A cryptographic signature carried by `Sign` and `Verify` terms.
///
/// In the logic, signatures are opaque byte strings; the `verify` judgment of
/// `Γ ⊢_K M : φ` (T2) is what relates them to the keyring `K`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Signature {
    /// Algorithm identifier (e.g. Ed25519 = 0).
    pub alg: u8,
    /// Raw signature bytes (64 for Ed25519).
    pub bytes: Vec<u8>,
}
