-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [dlc_d_rsm]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import DlcDRsm.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open dlc_d_rsm

/-- [dlc_core::rsm::{impl core::cmp::PartialEq<dlc_core::rsm::Command> for dlc_core::rsm::Command}::eq]:
    Source: 'crates/dlc-core/src/rsm.rs', lines 127:23-127:32
    Name pattern: [dlc_core::rsm::{core::cmp::PartialEq<dlc_core::rsm::Command, dlc_core::rsm::Command>}::eq]
    Visibility: public -/
@[rust_fun
  "dlc_core::rsm::{core::cmp::PartialEq<dlc_core::rsm::Command, dlc_core::rsm::Command>}::eq"]
axiom dlc_core.rsm.Command.Insts.CoreCmpPartialEqCommand.eq
  : dlc_core.rsm.Command → dlc_core.rsm.Command → Result Bool

