-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [dlc_d_rsm]: function definitions
import Aeneas
import DlcDRsm.Types
import DlcDRsm.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace dlc_d_rsm

/-- Trait implementation: [core::option::{impl core::fmt::Debug for core::option::Option<T>}]
    Source: '/rustc/library/core/src/option.rs', lines 591:15-591:20
    Name pattern: [core::fmt::Debug<core::option::Option<@T>>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<core::option::Option<@T>>"]
def core.option.Option.Insts.CoreFmtDebug {T : Type} (fmtDebugInst :
  core.fmt.Debug T) : core.fmt.Debug (Option T) := {
  fmt := core.option.Option.Insts.CoreFmtDebug.fmt fmtDebugInst
}

/-- Trait implementation: [dlc_core::syntax::{impl core::clone::Clone for dlc_core::syntax::Prop}]
    Source: 'crates/dlc-core/src/syntax.rs', lines 16:9-16:14
    Name pattern: [core::clone::Clone<dlc_core::syntax::Prop>] -/
@[reducible, rust_trait_impl "core::clone::Clone<dlc_core::syntax::Prop>"]
def dlc_core.syntax.Prop.Insts.CoreCloneClone : core.clone.Clone
  dlc_core.syntax.Prop := {
  clone := dlc_core.syntax.Prop.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [dlc_core::syntax::{impl core::fmt::Debug for dlc_core::syntax::Prop}]
    Source: 'crates/dlc-core/src/syntax.rs', lines 16:16-16:21
    Name pattern: [core::fmt::Debug<dlc_core::syntax::Prop>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<dlc_core::syntax::Prop>"]
def dlc_core.syntax.Prop.Insts.CoreFmtDebug : core.fmt.Debug
  dlc_core.syntax.Prop := {
  fmt := dlc_core.syntax.Prop.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [dlc_core::syntax::{impl core::cmp::PartialEq<dlc_core::syntax::Prop> for dlc_core::syntax::Prop}]
    Source: 'crates/dlc-core/src/syntax.rs', lines 16:23-16:32
    Name pattern: [core::cmp::PartialEq<dlc_core::syntax::Prop, dlc_core::syntax::Prop>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<dlc_core::syntax::Prop, dlc_core::syntax::Prop>"]
def dlc_core.syntax.Prop.Insts.CoreCmpPartialEqProp : core.cmp.PartialEq
  dlc_core.syntax.Prop dlc_core.syntax.Prop := {
  eq := dlc_core.syntax.Prop.Insts.CoreCmpPartialEqProp.eq
}

/-- Trait implementation: [dlc_core::syntax::{impl core::fmt::Debug for dlc_core::syntax::Term}]
    Source: 'crates/dlc-core/src/syntax.rs', lines 56:16-56:21
    Name pattern: [core::fmt::Debug<dlc_core::syntax::Term>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<dlc_core::syntax::Term>"]
def dlc_core.syntax.Term.Insts.CoreFmtDebug : core.fmt.Debug
  dlc_core.syntax.Term := {
  fmt := dlc_core.syntax.Term.Insts.CoreFmtDebug.fmt
}

/-- [dlc_d_rsm::budget::{impl core::clone::Clone for dlc_d_rsm::budget::FailureBudget}::clone]:
    Source: 'crates/dlc-d-rsm/src/budget.rs', lines 15:9-15:14
    Visibility: public -/
def budget.FailureBudget.Insts.CoreCloneClone.clone
  (self : budget.FailureBudget) : Result budget.FailureBudget := do
  let i ← lift (core.clone.impls.CloneU32.clone self.max_faults)
  let b ← lift (core.clone.impls.CloneBool.clone self.fair_delivery)
  let i1 ← lift (core.clone.impls.CloneU32.clone self.consumed)
  ok { max_faults := i, fair_delivery := b, consumed := i1 }

/-- Trait implementation: [dlc_d_rsm::budget::{impl core::clone::Clone for dlc_d_rsm::budget::FailureBudget}]
    Source: 'crates/dlc-d-rsm/src/budget.rs', lines 15:9-15:14 -/
@[reducible]
def budget.FailureBudget.Insts.CoreCloneClone : core.clone.Clone
  budget.FailureBudget := {
  clone := budget.FailureBudget.Insts.CoreCloneClone.clone
}

/-- [dlc_d_rsm::budget::{impl core::fmt::Debug for dlc_d_rsm::budget::FailureBudget}::fmt]:
    Source: 'crates/dlc-d-rsm/src/budget.rs', lines 15:16-15:21
    Visibility: public -/
def budget.FailureBudget.Insts.CoreFmtDebug.fmt
  (self : budget.FailureBudget) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU32 self.max_faults
  let dyn1 := Dyn.mk _ core.fmt.DebugBool self.fair_delivery
  let dyn2 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU32) self.consumed
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "FailureBudget")
    (toStr "max_faults") dyn (toStr "fair_delivery") dyn1 (toStr "consumed")
    dyn2

/-- Trait implementation: [dlc_d_rsm::budget::{impl core::fmt::Debug for dlc_d_rsm::budget::FailureBudget}]
    Source: 'crates/dlc-d-rsm/src/budget.rs', lines 15:16-15:21 -/
@[reducible]
def budget.FailureBudget.Insts.CoreFmtDebug : core.fmt.Debug
  budget.FailureBudget := {
  fmt := budget.FailureBudget.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [dlc_d_rsm::budget::{impl core::marker::StructuralPartialEq for dlc_d_rsm::budget::FailureBudget}]
    Source: 'crates/dlc-d-rsm/src/budget.rs', lines 15:23-15:32 -/
@[reducible]
def budget.FailureBudget.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq budget.FailureBudget := {
}

/-- [dlc_d_rsm::budget::{impl core::cmp::PartialEq<dlc_d_rsm::budget::FailureBudget> for dlc_d_rsm::budget::FailureBudget}::eq]:
    Source: 'crates/dlc-d-rsm/src/budget.rs', lines 15:23-15:32
    Visibility: public -/
def budget.FailureBudget.Insts.CoreCmpPartialEqFailureBudget.eq
  (self : budget.FailureBudget) (other : budget.FailureBudget) :
  Result Bool
  := do
  if self.max_faults = other.max_faults
  then
    if self.fair_delivery = other.fair_delivery
    then ok (self.consumed = other.consumed)
    else ok false
  else ok false

/-- Trait implementation: [dlc_d_rsm::budget::{impl core::cmp::PartialEq<dlc_d_rsm::budget::FailureBudget> for dlc_d_rsm::budget::FailureBudget}]
    Source: 'crates/dlc-d-rsm/src/budget.rs', lines 15:23-15:32 -/
@[reducible]
def budget.FailureBudget.Insts.CoreCmpPartialEqFailureBudget :
  core.cmp.PartialEq budget.FailureBudget budget.FailureBudget := {
  eq := budget.FailureBudget.Insts.CoreCmpPartialEqFailureBudget.eq
}

/-- [dlc_d_rsm::budget::{impl core::cmp::Eq for dlc_d_rsm::budget::FailureBudget}::assert_fields_are_eq]:
    Source: 'crates/dlc-d-rsm/src/budget.rs', lines 15:34-15:36
    Visibility: public -/
def budget.FailureBudget.Insts.CoreCmpEq.assert_fields_are_eq
  (self : budget.FailureBudget) : Result Unit := do
  ok ()

/-- Trait implementation: [dlc_d_rsm::budget::{impl core::cmp::Eq for dlc_d_rsm::budget::FailureBudget}]
    Source: 'crates/dlc-d-rsm/src/budget.rs', lines 15:34-15:36 -/
@[reducible]
def budget.FailureBudget.Insts.CoreCmpEq : core.cmp.Eq budget.FailureBudget
  := {
  partialEqInst := budget.FailureBudget.Insts.CoreCmpPartialEqFailureBudget
  assert_fields_are_eq :=
    budget.FailureBudget.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [dlc_d_rsm::budget::{dlc_d_rsm::budget::FailureBudget}::zero]:
    Source: 'crates/dlc-d-rsm/src/budget.rs', lines 30:4-36:5
    Visibility: public -/
def budget.FailureBudget.zero (f : Std.U32) : Result budget.FailureBudget := do
  ok { max_faults := f, fair_delivery := true, consumed := 0#u32 }

/-- [dlc_d_rsm::budget::{dlc_d_rsm::budget::FailureBudget}::saturating_add]:
    Source: 'crates/dlc-d-rsm/src/budget.rs', lines 41:4-47:5
    Visibility: public -/
def budget.FailureBudget.saturating_add
  (self : budget.FailureBudget) (extra : Std.U32) :
  Result budget.FailureBudget
  := do
  let i ← self.consumed + extra
  ok { self with consumed := i }

/-- [dlc_d_rsm::budget::{dlc_d_rsm::budget::FailureBudget}::le]:
    Source: 'crates/dlc-d-rsm/src/budget.rs', lines 51:4-53:5
    Visibility: public -/
def budget.FailureBudget.le (self : budget.FailureBudget) : Result Bool := do
  ok (self.consumed <= self.max_faults)

/-- [dlc_d_rsm::budget::{dlc_d_rsm::budget::FailureBudget}::within_contract]:
    Source: 'crates/dlc-d-rsm/src/budget.rs', lines 57:4-59:5
    Visibility: public -/
def budget.FailureBudget.within_contract
  (self : budget.FailureBudget) : Result Bool := do
  if self.fair_delivery
  then budget.FailureBudget.le self
  else ok false

/-- [dlc_d_rsm::consensus::is_quorum]:
    Source: 'crates/dlc-d-rsm/src/consensus.rs', lines 23:0-25:1
    Visibility: public -/
def consensus.is_quorum (card : Std.U32) (n : Std.U32) : Result Bool := do
  let i ← 2#u32 * card
  ok (i > n)

/-- [dlc_d_rsm::state::{impl core::cmp::PartialEq<dlc_d_rsm::state::Command> for dlc_d_rsm::state::Command}::eq]:
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 23:23-23:32
    Visibility: public -/
def state.Command.Insts.CoreCmpPartialEqCommand.eq
  (self : state.Command) (other : state.Command) : Result Bool := do
  let b ←
    dlc_core.syntax.Term.Insts.CoreCmpPartialEqTerm.eq self.payload
      other.payload
  if b
  then
    core.option.Option.Insts.CoreCmpPartialEqOption.eq
      dlc_core.syntax.Prop.Insts.CoreCmpPartialEqProp self.cap other.cap
  else ok false

/-- Trait implementation: [dlc_d_rsm::state::{impl core::cmp::PartialEq<dlc_d_rsm::state::Command> for dlc_d_rsm::state::Command}]
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 23:23-23:32 -/
@[reducible]
def state.Command.Insts.CoreCmpPartialEqCommand : core.cmp.PartialEq
  state.Command state.Command := {
  eq := state.Command.Insts.CoreCmpPartialEqCommand.eq
}

/-- [dlc_d_rsm::consensus::decided]: loop body 0:
    Source: 'crates/dlc-d-rsm/src/consensus.rs', lines 35:4-44:5
    Visibility: public -/
@[rust_loop_body]
def consensus.decided_loop.body
  (votes : Slice (Option state.Command)) (v : state.Command)
  (iter : core.ops.range.Range Std.Usize) (count : Std.U32) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Std.U32) Std.U32)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done count)
  | some i =>
    let o1 ← Slice.index_usize votes i
    match o1 with
    | none => ok (cont (iter1, count))
    | some c =>
      let b ← state.Command.Insts.CoreCmpPartialEqCommand.eq c v
      if b
      then let count1 ← count + 1#u32
           ok (cont (iter1, count1))
      else ok (cont (iter1, count))

/-- [dlc_d_rsm::consensus::decided]: loop 0:
    Source: 'crates/dlc-d-rsm/src/consensus.rs', lines 35:4-44:5
    Visibility: public -/
@[rust_loop]
def consensus.decided_loop
  (iter : core.ops.range.Range Std.Usize)
  (votes : Slice (Option state.Command)) (v : state.Command) (count : Std.U32)
  :
  Result Std.U32
  := do
  loop
    (fun (iter1, count1) => consensus.decided_loop.body votes v iter1 count1)
    (iter, count)

/-- [dlc_d_rsm::consensus::decided]:
    Source: 'crates/dlc-d-rsm/src/consensus.rs', lines 33:0-46:1
    Visibility: public -/
def consensus.decided
  (votes : Slice (Option state.Command)) (v : state.Command) :
  Result Bool
  := do
  let i := Slice.len votes
  let count ←
    consensus.decided_loop { start := 0#usize, «end» := i } votes v 0#u32
  let i1 := Slice.len votes
  let i2 ← lift (UScalar.cast .U32 i1)
  consensus.is_quorum count i2

/-- [dlc_d_rsm::state::APPLY_FUEL]
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 14:0-14:33
    Visibility: public -/
@[global_simps, irreducible] def state.APPLY_FUEL : Std.U32 := 1024#u32

/-- [dlc_d_rsm::state::{impl core::clone::Clone for dlc_d_rsm::state::Command}::clone]:
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 23:9-23:14
    Visibility: public -/
def state.Command.Insts.CoreCloneClone.clone
  (self : state.Command) : Result state.Command := do
  let t ← dlc_core.syntax.Term.Insts.CoreCloneClone.clone self.payload
  let o ←
    core.option.Option.Insts.CoreCloneClone.clone
      dlc_core.syntax.Prop.Insts.CoreCloneClone self.cap
  ok { payload := t, cap := o }

/-- Trait implementation: [dlc_d_rsm::state::{impl core::clone::Clone for dlc_d_rsm::state::Command}]
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 23:9-23:14 -/
@[reducible]
def state.Command.Insts.CoreCloneClone : core.clone.Clone state.Command := {
  clone := state.Command.Insts.CoreCloneClone.clone
}

/-- [dlc_d_rsm::state::{impl core::fmt::Debug for dlc_d_rsm::state::Command}::fmt]:
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 23:16-23:21
    Visibility: public -/
def state.Command.Insts.CoreFmtDebug.fmt
  (self : state.Command) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ dlc_core.syntax.Term.Insts.CoreFmtDebug self.payload
  let dyn1 :=
    Dyn.mk _ (core.fmt.DebugShared (core.option.Option.Insts.CoreFmtDebug
      dlc_core.syntax.Prop.Insts.CoreFmtDebug)) self.cap
  core.fmt.Formatter.debug_struct_field2_finish f (toStr "Command") (toStr
    "payload") dyn (toStr "cap") dyn1

/-- Trait implementation: [dlc_d_rsm::state::{impl core::fmt::Debug for dlc_d_rsm::state::Command}]
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 23:16-23:21 -/
@[reducible]
def state.Command.Insts.CoreFmtDebug : core.fmt.Debug state.Command := {
  fmt := state.Command.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [dlc_d_rsm::state::{impl core::marker::StructuralPartialEq for dlc_d_rsm::state::Command}]
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 23:23-23:32 -/
@[reducible]
def state.Command.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq state.Command := {
}

/-- [dlc_d_rsm::state::{impl core::cmp::Eq for dlc_d_rsm::state::Command}::assert_fields_are_eq]:
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 23:34-23:36
    Visibility: public -/
def state.Command.Insts.CoreCmpEq.assert_fields_are_eq
  (self : state.Command) : Result Unit := do
  ok ()

/-- Trait implementation: [dlc_d_rsm::state::{impl core::cmp::Eq for dlc_d_rsm::state::Command}]
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 23:34-23:36 -/
@[reducible]
def state.Command.Insts.CoreCmpEq : core.cmp.Eq state.Command := {
  partialEqInst := state.Command.Insts.CoreCmpPartialEqCommand
  assert_fields_are_eq := state.Command.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [dlc_d_rsm::state::{impl core::clone::Clone for dlc_d_rsm::state::Replica}::clone]:
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 36:9-36:14
    Visibility: public -/
def state.Replica.Insts.CoreCloneClone.clone
  (self : state.Replica) : Result state.Replica := do
  let i ← lift (core.clone.impls.CloneU32.clone self.id)
  let t ← dlc_core.syntax.Term.Insts.CoreCloneClone.clone self.store
  let i1 ← lift (core.clone.impls.CloneU32.clone self.applied)
  ok { id := i, store := t, applied := i1 }

/-- Trait implementation: [dlc_d_rsm::state::{impl core::clone::Clone for dlc_d_rsm::state::Replica}]
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 36:9-36:14 -/
@[reducible]
def state.Replica.Insts.CoreCloneClone : core.clone.Clone state.Replica := {
  clone := state.Replica.Insts.CoreCloneClone.clone
}

/-- [dlc_d_rsm::state::{impl core::fmt::Debug for dlc_d_rsm::state::Replica}::fmt]:
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 36:16-36:21
    Visibility: public -/
def state.Replica.Insts.CoreFmtDebug.fmt
  (self : state.Replica) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU32 self.id
  let dyn1 := Dyn.mk _ dlc_core.syntax.Term.Insts.CoreFmtDebug self.store
  let dyn2 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU32) self.applied
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "Replica") (toStr
    "id") dyn (toStr "store") dyn1 (toStr "applied") dyn2

/-- Trait implementation: [dlc_d_rsm::state::{impl core::fmt::Debug for dlc_d_rsm::state::Replica}]
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 36:16-36:21 -/
@[reducible]
def state.Replica.Insts.CoreFmtDebug : core.fmt.Debug state.Replica := {
  fmt := state.Replica.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [dlc_d_rsm::state::{impl core::marker::StructuralPartialEq for dlc_d_rsm::state::Replica}]
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 36:23-36:32 -/
@[reducible]
def state.Replica.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq state.Replica := {
}

/-- [dlc_d_rsm::state::{impl core::cmp::PartialEq<dlc_d_rsm::state::Replica> for dlc_d_rsm::state::Replica}::eq]:
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 36:23-36:32
    Visibility: public -/
def state.Replica.Insts.CoreCmpPartialEqReplica.eq
  (self : state.Replica) (other : state.Replica) : Result Bool := do
  if self.id = other.id
  then
    if self.applied = other.applied
    then
      dlc_core.syntax.Term.Insts.CoreCmpPartialEqTerm.eq self.store other.store
    else ok false
  else ok false

/-- Trait implementation: [dlc_d_rsm::state::{impl core::cmp::PartialEq<dlc_d_rsm::state::Replica> for dlc_d_rsm::state::Replica}]
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 36:23-36:32 -/
@[reducible]
def state.Replica.Insts.CoreCmpPartialEqReplica : core.cmp.PartialEq
  state.Replica state.Replica := {
  eq := state.Replica.Insts.CoreCmpPartialEqReplica.eq
}

/-- [dlc_d_rsm::state::{impl core::cmp::Eq for dlc_d_rsm::state::Replica}::assert_fields_are_eq]:
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 36:34-36:36
    Visibility: public -/
def state.Replica.Insts.CoreCmpEq.assert_fields_are_eq
  (self : state.Replica) : Result Unit := do
  ok ()

/-- Trait implementation: [dlc_d_rsm::state::{impl core::cmp::Eq for dlc_d_rsm::state::Replica}]
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 36:34-36:36 -/
@[reducible]
def state.Replica.Insts.CoreCmpEq : core.cmp.Eq state.Replica := {
  partialEqInst := state.Replica.Insts.CoreCmpPartialEqReplica
  assert_fields_are_eq := state.Replica.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [dlc_d_rsm::state::{impl core::clone::Clone for dlc_d_rsm::state::GlobalConfig}::clone]:
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 57:9-57:14
    Visibility: public -/
def state.GlobalConfig.Insts.CoreCloneClone.clone
  (self : state.GlobalConfig) : Result state.GlobalConfig := do
  let v ←
    alloc.vec.CloneVec.clone state.Replica.Insts.CoreCloneClone self.replicas
  let v1 ←
    alloc.vec.CloneVec.clone state.Command.Insts.CoreCloneClone self.log
  let fb ← budget.FailureBudget.Insts.CoreCloneClone.clone self.budget
  ok { replicas := v, log := v1, budget := fb }

/-- Trait implementation: [dlc_d_rsm::state::{impl core::clone::Clone for dlc_d_rsm::state::GlobalConfig}]
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 57:9-57:14 -/
@[reducible]
def state.GlobalConfig.Insts.CoreCloneClone : core.clone.Clone
  state.GlobalConfig := {
  clone := state.GlobalConfig.Insts.CoreCloneClone.clone
}

/-- [dlc_d_rsm::state::{impl core::fmt::Debug for dlc_d_rsm::state::GlobalConfig}::fmt]:
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 57:16-57:21
    Visibility: public -/
def state.GlobalConfig.Insts.CoreFmtDebug.fmt
  (self : state.GlobalConfig) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn :=
    Dyn.mk _ (core.fmt.DebugVec state.Replica.Insts.CoreFmtDebug) self.replicas
  let dyn1 :=
    Dyn.mk _ (core.fmt.DebugVec state.Command.Insts.CoreFmtDebug) self.log
  let dyn2 :=
    Dyn.mk _ (core.fmt.DebugShared budget.FailureBudget.Insts.CoreFmtDebug)
      self.budget
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "GlobalConfig") (toStr
    "replicas") dyn (toStr "log") dyn1 (toStr "budget") dyn2

/-- Trait implementation: [dlc_d_rsm::state::{impl core::fmt::Debug for dlc_d_rsm::state::GlobalConfig}]
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 57:16-57:21 -/
@[reducible]
def state.GlobalConfig.Insts.CoreFmtDebug : core.fmt.Debug state.GlobalConfig
  := {
  fmt := state.GlobalConfig.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [dlc_d_rsm::state::{impl core::marker::StructuralPartialEq for dlc_d_rsm::state::GlobalConfig}]
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 57:23-57:32 -/
@[reducible]
def state.GlobalConfig.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq state.GlobalConfig := {
}

/-- [dlc_d_rsm::state::{impl core::cmp::PartialEq<dlc_d_rsm::state::GlobalConfig> for dlc_d_rsm::state::GlobalConfig}::eq]:
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 57:23-57:32
    Visibility: public -/
def state.GlobalConfig.Insts.CoreCmpPartialEqGlobalConfig.eq
  (self : state.GlobalConfig) (other : state.GlobalConfig) : Result Bool := do
  let b ←
    alloc.vec.partial_eq.PartialEqVec.eq
      state.Replica.Insts.CoreCmpPartialEqReplica self.replicas other.replicas
  if b
  then
    let b1 ←
      alloc.vec.partial_eq.PartialEqVec.eq
        state.Command.Insts.CoreCmpPartialEqCommand self.log other.log
    if b1
    then
      budget.FailureBudget.Insts.CoreCmpPartialEqFailureBudget.eq self.budget
        other.budget
    else ok false
  else ok false

/-- Trait implementation: [dlc_d_rsm::state::{impl core::cmp::PartialEq<dlc_d_rsm::state::GlobalConfig> for dlc_d_rsm::state::GlobalConfig}]
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 57:23-57:32 -/
@[reducible]
def state.GlobalConfig.Insts.CoreCmpPartialEqGlobalConfig : core.cmp.PartialEq
  state.GlobalConfig state.GlobalConfig := {
  eq := state.GlobalConfig.Insts.CoreCmpPartialEqGlobalConfig.eq
}

/-- [dlc_d_rsm::state::{impl core::cmp::Eq for dlc_d_rsm::state::GlobalConfig}::assert_fields_are_eq]:
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 57:34-57:36
    Visibility: public -/
def state.GlobalConfig.Insts.CoreCmpEq.assert_fields_are_eq
  (self : state.GlobalConfig) : Result Unit := do
  ok ()

/-- Trait implementation: [dlc_d_rsm::state::{impl core::cmp::Eq for dlc_d_rsm::state::GlobalConfig}]
    Source: 'crates/dlc-d-rsm/src/state.rs', lines 57:34-57:36 -/
@[reducible]
def state.GlobalConfig.Insts.CoreCmpEq : core.cmp.Eq state.GlobalConfig := {
  partialEqInst := state.GlobalConfig.Insts.CoreCmpPartialEqGlobalConfig
  assert_fields_are_eq :=
    state.GlobalConfig.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [dlc_d_rsm::transition::apply_command]:
    Source: 'crates/dlc-d-rsm/src/transition.rs', lines 27:0-30:1
    Visibility: public -/
def transition.apply_command
  (c : state.Command) (s : dlc_core.syntax.Term) :
  Result dlc_core.syntax.Term
  := do
  let t ← dlc_core.syntax.Term.Insts.CoreCloneClone.clone c.payload
  let t1 ← dlc_core.syntax.Term.Insts.CoreCloneClone.clone s
  let (t2, _) ←
    dlc_core.reduce.reduce_with_fuel (dlc_core.syntax.Term.App t t1)
      state.APPLY_FUEL
  ok t2

/-- [dlc_d_rsm::transition::apply_prefix]: loop body 0:
    Source: 'crates/dlc-d-rsm/src/transition.rs', lines 39:4-41:5
    Visibility: public -/
@[rust_loop_body]
def transition.apply_prefix_loop.body
  (cmds : Slice state.Command) (iter : core.ops.range.Range Std.Usize)
  (acc : dlc_core.syntax.Term) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) ×
    dlc_core.syntax.Term) dlc_core.syntax.Term)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done acc)
  | some i =>
    let c ← Slice.index_usize cmds i
    let acc1 ← transition.apply_command c acc
    ok (cont (iter1, acc1))

/-- [dlc_d_rsm::transition::apply_prefix]: loop 0:
    Source: 'crates/dlc-d-rsm/src/transition.rs', lines 39:4-41:5
    Visibility: public -/
@[rust_loop]
def transition.apply_prefix_loop
  (iter : core.ops.range.Range Std.Usize) (cmds : Slice state.Command)
  (acc : dlc_core.syntax.Term) :
  Result dlc_core.syntax.Term
  := do
  loop
    (fun (iter1, acc1) => transition.apply_prefix_loop.body cmds iter1 acc1)
    (iter, acc)

/-- [dlc_d_rsm::transition::apply_prefix]:
    Source: 'crates/dlc-d-rsm/src/transition.rs', lines 37:0-43:1
    Visibility: public -/
def transition.apply_prefix
  (init : dlc_core.syntax.Term) (cmds : Slice state.Command) :
  Result dlc_core.syntax.Term
  := do
  let acc ← dlc_core.syntax.Term.Insts.CoreCloneClone.clone init
  let i := Slice.len cmds
  transition.apply_prefix_loop { start := 0#usize, «end» := i } cmds acc

/-- [dlc_d_rsm::transition::deliver]:
    Source: 'crates/dlc-d-rsm/src/transition.rs', lines 51:0-60:1
    Visibility: public -/
def transition.deliver
  (log : alloc.vec.Vec state.Command) (r : state.Replica) :
  Result state.Replica
  := do
  let s := alloc.vec.Vec.deref log
  let i ← lift (UScalar.cast .Usize r.applied)
  let o ←
    core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice state.Command)
      s i
  match o with
  | none => state.Replica.Insts.CoreCloneClone.clone r
  | some c =>
    let t ← transition.apply_command c r.store
    let i1 ← r.applied + 1#u32
    ok { r with store := t, applied := i1 }

/-- [dlc_d_rsm::transition::world_step]: loop body 0:
    Source: 'crates/dlc-d-rsm/src/transition.rs', lines 73:4-75:5
    Visibility: public -/
@[rust_loop_body]
def transition.world_step_loop.body
  (v : alloc.vec.Vec state.Replica) (v1 : alloc.vec.Vec state.Command)
  (iter : core.ops.range.Range Std.Usize)
  (stepped : alloc.vec.Vec state.Replica) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (alloc.vec.Vec
    state.Replica)) (alloc.vec.Vec state.Replica))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done stepped)
  | some i =>
    let r ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice state.Replica)
        v i
    let r1 ← transition.deliver v1 r
    let stepped1 ← alloc.vec.Vec.push stepped r1
    ok (cont (iter1, stepped1))

/-- [dlc_d_rsm::transition::world_step]: loop 0:
    Source: 'crates/dlc-d-rsm/src/transition.rs', lines 73:4-75:5
    Visibility: public -/
@[rust_loop]
def transition.world_step_loop
  (iter : core.ops.range.Range Std.Usize) (v : alloc.vec.Vec state.Replica)
  (v1 : alloc.vec.Vec state.Command) (stepped : alloc.vec.Vec state.Replica) :
  Result (alloc.vec.Vec state.Replica)
  := do
  loop
    (fun (iter1, stepped1) => transition.world_step_loop.body v v1 iter1
      stepped1)
    (iter, stepped)

/-- [dlc_d_rsm::transition::world_step]:
    Source: 'crates/dlc-d-rsm/src/transition.rs', lines 71:0-81:1
    Visibility: public -/
def transition.world_step
  (g : state.GlobalConfig) : Result state.GlobalConfig := do
  let i := alloc.vec.Vec.len g.replicas
  let stepped ←
    transition.world_step_loop { start := 0#usize, «end» := i } g.replicas
      g.log (alloc.vec.Vec.new state.Replica)
  let v ← alloc.vec.CloneVec.clone state.Command.Insts.CoreCloneClone g.log
  let fb ← budget.FailureBudget.Insts.CoreCloneClone.clone g.budget
  ok { replicas := stepped, log := v, budget := fb }

/-- [dlc_d_rsm::transition::commit]:
    Source: 'crates/dlc-d-rsm/src/transition.rs', lines 90:0-98:1
    Visibility: public -/
def transition.commit
  (g : state.GlobalConfig) (c : state.Command) :
  Result state.GlobalConfig
  := do
  let log ← alloc.vec.CloneVec.clone state.Command.Insts.CoreCloneClone g.log
  let log1 ← alloc.vec.Vec.push log c
  let v ←
    alloc.vec.CloneVec.clone state.Replica.Insts.CoreCloneClone g.replicas
  let fb ← budget.FailureBudget.Insts.CoreCloneClone.clone g.budget
  ok { replicas := v, log := log1, budget := fb }

end dlc_d_rsm
