-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [dlc_d_rsm]: function definitions
import Aeneas
import DlcDRsm.Types
import DlcDRsm.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace dlc_d_rsm

/-- Trait implementation: [dlc_core::rsm::{impl core::cmp::PartialEq<dlc_core::rsm::Command> for dlc_core::rsm::Command}]
    Source: 'crates/dlc-core/src/rsm.rs', lines 127:23-127:32
    Name pattern: [core::cmp::PartialEq<dlc_core::rsm::Command, dlc_core::rsm::Command>] -/
@[reducible, rust_trait_impl
  "core::cmp::PartialEq<dlc_core::rsm::Command, dlc_core::rsm::Command>"]
def dlc_core.rsm.Command.Insts.CoreCmpPartialEqCommand : core.cmp.PartialEq
  dlc_core.rsm.Command dlc_core.rsm.Command := {
  eq := dlc_core.rsm.Command.Insts.CoreCmpPartialEqCommand.eq
}

/-- [dlc_d_rsm::consensus::is_quorum]:
    Source: 'crates/dlc-d-rsm/src/consensus.rs', lines 23:0-25:1
    Visibility: public -/
def consensus.is_quorum (card : Std.U32) (n : Std.U32) : Result Bool := do
  let i ← 2#u32 * card
  ok (i > n)

/-- [dlc_d_rsm::consensus::is_byz_quorum]:
    Source: 'crates/dlc-d-rsm/src/consensus.rs', lines 39:0-41:1
    Visibility: public -/
def consensus.is_byz_quorum (card : Std.U32) (n : Std.U32) : Result Bool := do
  let i ← 3#u32 * card
  let i1 ← 2#u32 * n
  ok (i > i1)

/-- [dlc_d_rsm::consensus::decided]: loop body 0:
    Source: 'crates/dlc-d-rsm/src/consensus.rs', lines 58:4-67:5
    Visibility: public -/
@[rust_loop_body]
def consensus.decided_loop.body
  (votes : Slice (Option dlc_core.rsm.Command)) (v : dlc_core.rsm.Command)
  (iter : core.ops.range.Range Std.Usize) (count : Std.U32) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Std.U32) Std.U32)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done count)
  | some i =>
    let o1 ← Slice.index_usize votes i
    match o1 with
    | none => ok (cont (iter1, count))
    | some c =>
      let b ← dlc_core.rsm.Command.Insts.CoreCmpPartialEqCommand.eq c v
      if b
      then let count1 ← count + 1#u32
           ok (cont (iter1, count1))
      else ok (cont (iter1, count))

/-- [dlc_d_rsm::consensus::decided]: loop 0:
    Source: 'crates/dlc-d-rsm/src/consensus.rs', lines 58:4-67:5
    Visibility: public -/
@[rust_loop]
def consensus.decided_loop
  (iter : core.ops.range.Range Std.Usize)
  (votes : Slice (Option dlc_core.rsm.Command)) (v : dlc_core.rsm.Command)
  (count : Std.U32) :
  Result Std.U32
  := do
  loop
    (fun (iter1, count1) => consensus.decided_loop.body votes v iter1 count1)
    (iter, count)

/-- [dlc_d_rsm::consensus::decided]:
    Source: 'crates/dlc-d-rsm/src/consensus.rs', lines 56:0-69:1
    Visibility: public -/
def consensus.decided
  (votes : Slice (Option dlc_core.rsm.Command)) (v : dlc_core.rsm.Command) :
  Result Bool
  := do
  let i := Slice.len votes
  let count ←
    consensus.decided_loop { start := 0#usize, «end» := i } votes v 0#u32
  let i1 := Slice.len votes
  let i2 ← lift (UScalar.cast .U32 i1)
  consensus.is_quorum count i2

/-- [dlc_d_rsm::consensus::byz_decided]: loop body 0:
    Source: 'crates/dlc-d-rsm/src/consensus.rs', lines 81:4-90:5
    Visibility: public -/
@[rust_loop_body]
def consensus.byz_decided_loop.body
  (votes : Slice (Option dlc_core.rsm.Command)) (v : dlc_core.rsm.Command)
  (iter : core.ops.range.Range Std.Usize) (count : Std.U32) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Std.U32) Std.U32)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done count)
  | some i =>
    let o1 ← Slice.index_usize votes i
    match o1 with
    | none => ok (cont (iter1, count))
    | some c =>
      let b ← dlc_core.rsm.Command.Insts.CoreCmpPartialEqCommand.eq c v
      if b
      then let count1 ← count + 1#u32
           ok (cont (iter1, count1))
      else ok (cont (iter1, count))

/-- [dlc_d_rsm::consensus::byz_decided]: loop 0:
    Source: 'crates/dlc-d-rsm/src/consensus.rs', lines 81:4-90:5
    Visibility: public -/
@[rust_loop]
def consensus.byz_decided_loop
  (iter : core.ops.range.Range Std.Usize)
  (votes : Slice (Option dlc_core.rsm.Command)) (v : dlc_core.rsm.Command)
  (count : Std.U32) :
  Result Std.U32
  := do
  loop
    (fun (iter1, count1) => consensus.byz_decided_loop.body votes v iter1
      count1)
    (iter, count)

/-- [dlc_d_rsm::consensus::byz_decided]:
    Source: 'crates/dlc-d-rsm/src/consensus.rs', lines 79:0-92:1
    Visibility: public -/
def consensus.byz_decided
  (votes : Slice (Option dlc_core.rsm.Command)) (v : dlc_core.rsm.Command) :
  Result Bool
  := do
  let i := Slice.len votes
  let count ←
    consensus.byz_decided_loop { start := 0#usize, «end» := i } votes v 0#u32
  let i1 := Slice.len votes
  let i2 ← lift (UScalar.cast .U32 i1)
  consensus.is_byz_quorum count i2

end dlc_d_rsm
