-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [dlc_d_rsm]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace dlc_d_rsm

/-- [dlc_core::ifc::Label]
    Source: 'crates/dlc-core/src/ifc.rs', lines 14:0-14:16
    Name pattern: [dlc_core::ifc::Label]
    Visibility: public -/
@[reducible, rust_type "dlc_core::ifc::Label"]
def dlc_core.ifc.Label := alloc.vec.Vec Std.U32

/-- [dlc_core::time::TimeBound]
    Source: 'crates/dlc-core/src/time.rs', lines 13:0-13:20
    Name pattern: [dlc_core::time::TimeBound]
    Visibility: public -/
@[rust_type "dlc_core::time::TimeBound"]
structure dlc_core.time.TimeBound where
  epoch_ms : Std.U64

/-- [dlc_core::principal::PrincipalId]
    Source: 'crates/dlc-core/src/principal.rs', lines 26:0-26:22
    Name pattern: [dlc_core::principal::PrincipalId]
    Visibility: public -/
@[reducible, rust_type "dlc_core::principal::PrincipalId"]
def dlc_core.principal.PrincipalId := Array Std.U8 32#usize

/-- [dlc_core::principal::Principal]
    Source: 'crates/dlc-core/src/principal.rs', lines 9:0-9:18
    Name pattern: [dlc_core::principal::Principal]
    Visibility: public -/
@[discriminant isize, rust_type "dlc_core::principal::Principal"]
inductive dlc_core.principal.Principal where
| Atom : dlc_core.principal.PrincipalId → dlc_core.principal.Principal
| And :
  dlc_core.principal.Principal →
  dlc_core.principal.Principal →
  dlc_core.principal.Principal
| Or :
  dlc_core.principal.Principal →
  dlc_core.principal.Principal →
  dlc_core.principal.Principal
| Acting :
  dlc_core.principal.Principal →
  dlc_core.principal.Principal →
  dlc_core.principal.Principal

/-- [dlc_core::obligation::DpBudget]
    Source: 'crates/dlc-core/src/obligation.rs', lines 52:0-52:19
    Name pattern: [dlc_core::obligation::DpBudget]
    Visibility: public -/
@[rust_type "dlc_core::obligation::DpBudget"]
structure dlc_core.obligation.DpBudget where
  epsilon_micros : Std.U64
  delta_micros : Std.U64

/-- [dlc_core::obligation::ActionId]
    Source: 'crates/dlc-core/src/obligation.rs', lines 42:0-42:19
    Name pattern: [dlc_core::obligation::ActionId]
    Visibility: public -/
@[reducible, rust_type "dlc_core::obligation::ActionId"]
def dlc_core.obligation.ActionId := alloc.vec.Vec Std.U8

/-- [dlc_core::obligation::Obligation]
    Source: 'crates/dlc-core/src/obligation.rs', lines 21:0-21:19
    Name pattern: [dlc_core::obligation::Obligation]
    Visibility: public -/
@[discriminant isize, rust_type "dlc_core::obligation::Obligation"]
inductive dlc_core.obligation.Obligation where
| Top : dlc_core.obligation.Obligation
| Bot : dlc_core.obligation.Obligation
| ActOf :
  dlc_core.principal.Principal →
  dlc_core.obligation.ActionId →
  dlc_core.obligation.Obligation
| Within : dlc_core.time.TimeBound → dlc_core.obligation.Obligation
| Tensor :
  dlc_core.obligation.Obligation →
  dlc_core.obligation.Obligation →
  dlc_core.obligation.Obligation
| Lolli :
  dlc_core.obligation.Obligation →
  dlc_core.obligation.Obligation →
  dlc_core.obligation.Obligation
| DpBudget : dlc_core.obligation.DpBudget → dlc_core.obligation.Obligation

/-- [dlc_core::syntax::Signature]
    Source: 'crates/dlc-core/src/syntax.rs', lines 168:0-168:20
    Name pattern: [dlc_core::syntax::Signature]
    Visibility: public -/
@[rust_type "dlc_core::syntax::Signature"]
structure dlc_core.syntax.Signature where
  alg : Std.U8
  bytes : alloc.vec.Vec Std.U8

/-- [dlc_core::syntax::Prop]
    Source: 'crates/dlc-core/src/syntax.rs', lines 17:0-17:13
    Name pattern: [dlc_core::syntax::Prop]
    Visibility: public -/
@[discriminant isize, rust_type "dlc_core::syntax::Prop"]
inductive dlc_core.syntax.Prop where
| Top : dlc_core.syntax.Prop
| Bot : dlc_core.syntax.Prop
| Atom : Std.U32 → dlc_core.syntax.Prop
| Imp : dlc_core.syntax.Prop → dlc_core.syntax.Prop → dlc_core.syntax.Prop
| And : dlc_core.syntax.Prop → dlc_core.syntax.Prop → dlc_core.syntax.Prop
| Or : dlc_core.syntax.Prop → dlc_core.syntax.Prop → dlc_core.syntax.Prop
| Says :
  dlc_core.principal.Principal →
  dlc_core.syntax.Prop →
  dlc_core.syntax.Prop
| SpeaksFor :
  dlc_core.principal.Principal →
  dlc_core.principal.Principal →
  dlc_core.syntax.Prop
| At : dlc_core.syntax.Prop → dlc_core.ifc.Label → dlc_core.syntax.Prop
| Boxed :
  dlc_core.obligation.Obligation →
  dlc_core.syntax.Prop →
  dlc_core.syntax.Prop
| Within :
  dlc_core.time.TimeBound →
  dlc_core.syntax.Prop →
  dlc_core.syntax.Prop
| Tensor :
  dlc_core.syntax.Prop →
  dlc_core.syntax.Prop →
  dlc_core.syntax.Prop
| Lolli :
  dlc_core.syntax.Prop →
  dlc_core.syntax.Prop →
  dlc_core.syntax.Prop
| Replicated :
  dlc_core.syntax.Prop →
  dlc_core.ifc.Label →
  dlc_core.syntax.Prop

/-- [dlc_core::syntax::Term]
    Source: 'crates/dlc-core/src/syntax.rs', lines 57:0-57:13
    Name pattern: [dlc_core::syntax::Term]
    Visibility: public -/
@[discriminant isize, rust_type "dlc_core::syntax::Term"]
inductive dlc_core.syntax.Term where
| Var : Std.U32 → dlc_core.syntax.Term
| Lam : dlc_core.syntax.Prop → dlc_core.syntax.Term → dlc_core.syntax.Term
| App : dlc_core.syntax.Term → dlc_core.syntax.Term → dlc_core.syntax.Term
| Sign :
  dlc_core.principal.Principal →
  dlc_core.syntax.Term →
  dlc_core.syntax.Signature →
  dlc_core.syntax.Term
| Verify :
  dlc_core.principal.Principal →
  dlc_core.syntax.Term →
  dlc_core.syntax.Signature →
  dlc_core.syntax.Term
| Delegate :
  dlc_core.syntax.Term →
  dlc_core.syntax.Term →
  dlc_core.syntax.Term
| Attenuate :
  dlc_core.syntax.Term →
  dlc_core.syntax.Prop →
  dlc_core.syntax.Term
| SaysBind :
  dlc_core.principal.Principal →
  dlc_core.syntax.Term →
  dlc_core.syntax.Term →
  dlc_core.syntax.Term
| Boxed :
  dlc_core.obligation.Obligation →
  dlc_core.syntax.Term →
  dlc_core.syntax.Term →
  dlc_core.syntax.Term
| Discharge :
  dlc_core.syntax.Term →
  dlc_core.syntax.Term →
  dlc_core.syntax.Term
| LiftLabel :
  dlc_core.ifc.Label →
  dlc_core.syntax.Term →
  dlc_core.syntax.Term
| Declassify :
  dlc_core.ifc.Label →
  dlc_core.syntax.Term →
  dlc_core.syntax.Term →
  dlc_core.syntax.Term
| Now : dlc_core.time.TimeBound → dlc_core.syntax.Term
| WithinIntro :
  dlc_core.time.TimeBound →
  dlc_core.syntax.Term →
  dlc_core.syntax.Term
| Pair : dlc_core.syntax.Term → dlc_core.syntax.Term → dlc_core.syntax.Term
| Fst : dlc_core.syntax.Term → dlc_core.syntax.Term
| Snd : dlc_core.syntax.Term → dlc_core.syntax.Term
| Inl : dlc_core.syntax.Prop → dlc_core.syntax.Term → dlc_core.syntax.Term
| Inr : dlc_core.syntax.Prop → dlc_core.syntax.Term → dlc_core.syntax.Term
| Case :
  dlc_core.syntax.Term →
  dlc_core.syntax.Term →
  dlc_core.syntax.Term →
  dlc_core.syntax.Term
| TensorIntro :
  dlc_core.syntax.Term →
  dlc_core.syntax.Term →
  dlc_core.syntax.Term
| LetTensor :
  dlc_core.syntax.Term →
  dlc_core.syntax.Term →
  dlc_core.syntax.Term
| LetSays :
  dlc_core.principal.Principal →
  dlc_core.syntax.Term →
  dlc_core.syntax.Term →
  dlc_core.syntax.Term
| SfExtract : dlc_core.syntax.Term → dlc_core.syntax.Term
| Command :
  dlc_core.syntax.Term →
  dlc_core.syntax.Term →
  dlc_core.ifc.Label →
  dlc_core.syntax.Term
| RunCmd :
  dlc_core.syntax.Term →
  dlc_core.syntax.Term →
  dlc_core.syntax.Term

/-- [dlc_core::rsm::Command]
    Source: 'crates/dlc-core/src/rsm.rs', lines 128:0-128:18
    Name pattern: [dlc_core::rsm::Command]
    Visibility: public -/
@[rust_type "dlc_core::rsm::Command"]
structure dlc_core.rsm.Command where
  payload : dlc_core.syntax.Term
  cap : Option dlc_core.syntax.Prop

end dlc_d_rsm
