[package]
name = "dlc-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "`dlc` CLI for issuing and verifying DLC proof terms"

[[bin]]
name = "dlc"
path = "src/main.rs"

[dependencies]
dlc-core = { path = "../dlc-core", version = "0.0.1" }
dlc-crypto = { path = "../dlc-crypto", version = "0.0.1" }
dlc-protocol = { path = "../dlc-protocol", version = "0.0.1" }
dlc-verifier = { path = "../dlc-verifier", version = "0.0.1" }
