/-
Aeneas-generated translation of `crates/dlc-core`.

This file is REGENERATED by `scripts/aeneas-translate.sh` and should not be
hand-edited. CI runs the regeneration on every PR and blocks merge if the
diff is non-clean.

The Week-1 placeholder is replaced by Charon's emission once the Aeneas
pipeline is wired up at M1.Q1.d.
-/

namespace DLC.Aeneas.DlcCore

/-- Placeholder root symbol so `lake build` succeeds before M1.Q1.d. -/
def placeholder : Unit := ()

end DLC.Aeneas.DlcCore
