#!/usr/bin/env bash
# scripts/check-axioms.sh — compare `#print axioms` output for each
# tracked theorem against `lean/expected-axioms/<theorem>.txt`.
#
# Fails on ANY difference. New axioms must be:
#   (a) intentional (docstring justifies),
#   (b) the snapshot updated in the same PR.
#
# This catches silent soundness regressions where a refactor accidentally
# introduces a new axiom dependency (e.g. a hidden `sorry`, an opaque
# definition load-bearing for a proof, or a misuse of `noncomputable def`).

set -euo pipefail

cd "$(dirname "$0")/.."

EXPECTED_DIR="lean/expected-axioms"
LEAN_DIR="lean"
# Path relative to repo root (used to write the file).
SCRIPT_DIR="lean/.print-axioms"
# Path relative to LEAN_DIR (used when invoking `lake env lean` from inside lean/).
SCRIPT_DIR_REL=".print-axioms"

# Each theorem is tracked as `lean/expected-axioms/<snapshot>.txt`.
# The theorem's fully-qualified name is NOT inferred from the filename —
# it is read from the snapshot's FIRST LINE, which has the shape
#   '<FQN>' depends on axioms: [...]        (or "does not depend ...")
# and names the theorem inside single quotes. This lets a single script
# cover BOTH `DLC.*` snapshots (filename == theorem short name, e.g.
# `t3_two_run_general.txt`) and `DLCD.*` snapshots (keyed by a `dlcd-<name>`
# filename whose first line is the authoritative `'DLCD.<name>' ...`).

mkdir -p "$SCRIPT_DIR"

# Generate a one-off Lean script that prints axioms for all tracked theorems.
# Parallel arrays: SNAP_FILES[i] is a snapshot path, SNAP_FQNS[i] its FQN.
SNAP_FILES=()
SNAP_FQNS=()
for f in "$EXPECTED_DIR"/*.txt; do
  [ -f "$f" ] || continue
  # Extract the FQN from between the first pair of single quotes on the
  # first non-blank line.
  fqn="$(sed -n "s/^'\\([^']*\\)'.*/\\1/p" "$f" | head -1)"
  if [ -z "$fqn" ]; then
    echo "check-axioms: cannot parse FQN from first line of $f" >&2
    exit 1
  fi
  SNAP_FILES+=("$f")
  SNAP_FQNS+=("$fqn")
done

if [ ${#SNAP_FILES[@]} -eq 0 ]; then
  echo "check-axioms: no snapshots in $EXPECTED_DIR/ — nothing to check"
  exit 0
fi

# Construct a single Lean file that imports the tracked libraries and prints
# axioms. `DLCD.Summary` transitively imports every `DLCD.*` module.
SCRIPT_FILE="$SCRIPT_DIR/PrintAll.lean"
{
  echo "-- Auto-generated by scripts/check-axioms.sh — do not commit."
  echo "import DLC.Decidability"
  echo "import DLC.Correspondence"
  echo "import DLC.NonInterference"
  echo "import DLC.ObligationSoundness"
  echo "import DLC.Reduce"
  echo "import DLC.ProtocolCorrespondence"
  echo "import DLC.IndexedMonad"
  echo "import DLC.Witness.AxiomAudit"
  echo "import DLC.NonInterferenceTwoRun"
  echo "import DLC.ReduceMeta"
  echo "import DLC.Progress"
  echo "import DLC.NonInterferenceLR"
  echo "import DLC.NonInterferenceEnv"
  echo "import DLC.NonInterferenceFundamental"
  echo "import DLC.CtxWellFormed"
  echo "import DLCD.Summary"
  # R2.2b: the anti-vacuity witness `appCommandRefines_witness` lives here
  # (imports the DlcCore Aeneas tree). NOT DLCD.CorrespondenceConsensus — the
  # two generated trees cannot co-elaborate in one module.
  echo "import DLCD.Correspondence"
  echo ""
  for fqn in "${SNAP_FQNS[@]}"; do
    echo "#print axioms $fqn"
  done
} > "$SCRIPT_FILE"

# Run lake/lean and capture stdout. Inside `cd lean`, the path is relative.
ACTUAL_FILE="$SCRIPT_DIR/actual.txt"
(cd "$LEAN_DIR" && lake env lean "$SCRIPT_DIR_REL/PrintAll.lean") > "$ACTUAL_FILE" || {
  echo "check-axioms: lake env lean failed — see stderr above" >&2
  exit 1
}

# Compare each theorem's actual `#print axioms` line against its snapshot.
# `#print axioms X` produces exactly ONE line:
#   '<FQN>' depends on axioms: [foo, bar, ...]
# Grep for that line (anchored on the quoted FQN), diff against snapshot.
MISMATCH=0
i=0
while [ "$i" -lt "${#SNAP_FILES[@]}" ]; do
  expected="${SNAP_FILES[$i]}"
  fqn="${SNAP_FQNS[$i]}"
  i=$((i + 1))
  # Use fgrep with the leading quote+FQN to avoid partial matches.
  # `#print axioms X` has two output forms:
  #   '<FQN>' depends on axioms: [propext, ...]           (when ≥1 axiom)
  #   '<FQN>' does not depend on any axioms                (when 0 axioms)
  # Match either by anchoring on the leading quoted name.
  # `|| true` because under `set -o pipefail` a no-match grep aborts the
  # whole script; we want to emit a MISMATCH message instead.
  actual_line=$(grep -F "'$fqn'" "$ACTUAL_FILE" 2>/dev/null | head -1 || true)
  if [ -z "$actual_line" ]; then
    echo "check-axioms: MISMATCH — no #print output for $fqn" >&2
    MISMATCH=1
    continue
  fi
  expected_line=$(sed '/^$/d' "$expected" | head -1)
  if [ "$actual_line" != "$expected_line" ]; then
    echo "check-axioms: MISMATCH on $fqn ($(basename "$expected"))" >&2
    echo "  expected: $expected_line" >&2
    echo "  actual:   $actual_line" >&2
    MISMATCH=1
  fi
done

if [ "$MISMATCH" -eq 1 ]; then
  echo "" >&2
  echo "--- actual `lake env lean` stdout ---" >&2
  cat "$ACTUAL_FILE" >&2
  echo "--- end actual ---" >&2
  echo "" >&2
  echo "ERROR: axiom snapshot drift detected." >&2
  echo "If the change is intentional, regenerate via:" >&2
  echo "  cd lean && lake env lean $SCRIPT_FILE > /tmp/actual.txt" >&2
  echo "  # then update lean/expected-axioms/*.txt accordingly" >&2
  exit 1
fi

echo "check-axioms: ✓ all ${#SNAP_FILES[@]} snapshots match"
