#!/usr/bin/env bash
# scripts/check-axioms.sh — compare `#print axioms` output for each
# tracked theorem against `lean/expected-axioms/<theorem>.txt`.
#
# Fails on ANY difference. New axioms must be:
#   (a) intentional (docstring justifies),
#   (b) the snapshot updated in the same PR.
#
# This catches silent soundness regressions where a refactor accidentally
# introduces a new axiom dependency (e.g. a hidden `sorry`, an opaque
# definition load-bearing for a proof, or a misuse of `noncomputable def`).

set -euo pipefail

cd "$(dirname "$0")/.."

EXPECTED_DIR="lean/expected-axioms"
LEAN_DIR="lean"
# Path relative to repo root (used to write the file).
SCRIPT_DIR="lean/.print-axioms"
# Path relative to LEAN_DIR (used when invoking `lake env lean` from inside lean/).
SCRIPT_DIR_REL=".print-axioms"

# Each theorem is tracked as `lean/expected-axioms/<theorem>.txt`.
# The theorem's fully-qualified name is `DLC.<theorem>` (or whatever the
# snapshot's first line names).

mkdir -p "$SCRIPT_DIR"

# Generate a one-off Lean script that prints axioms for all tracked theorems.
THEOREMS=()
for f in "$EXPECTED_DIR"/*.txt; do
  [ -f "$f" ] || continue
  base="$(basename "$f" .txt)"
  THEOREMS+=("$base")
done

if [ ${#THEOREMS[@]} -eq 0 ]; then
  echo "check-axioms: no snapshots in $EXPECTED_DIR/ — nothing to check"
  exit 0
fi

# Construct a single Lean file that imports DLC and prints axioms.
SCRIPT_FILE="$SCRIPT_DIR/PrintAll.lean"
{
  echo "-- Auto-generated by scripts/check-axioms.sh — do not commit."
  echo "import DLC.Decidability"
  echo "import DLC.Correspondence"
  echo "import DLC.NonInterference"
  echo "import DLC.ObligationSoundness"
  echo "import DLC.Reduce"
  echo "import DLC.ProtocolCorrespondence"
  echo "import DLC.IndexedMonad"
  echo "import DLC.Witness.AxiomAudit"
  echo "import DLC.NonInterferenceTwoRun"
  echo "import DLC.ReduceMeta"
  echo "import DLC.Progress"
  echo "import DLC.NonInterferenceLR"
  echo "import DLC.NonInterferenceEnv"
  echo "import DLC.NonInterferenceFundamental"
  echo ""
  for t in "${THEOREMS[@]}"; do
    echo "#print axioms DLC.$t"
  done
} > "$SCRIPT_FILE"

# Run lake/lean and capture stdout. Inside `cd lean`, the path is relative.
ACTUAL_FILE="$SCRIPT_DIR/actual.txt"
(cd "$LEAN_DIR" && lake env lean "$SCRIPT_DIR_REL/PrintAll.lean") > "$ACTUAL_FILE" || {
  echo "check-axioms: lake env lean failed — see stderr above" >&2
  exit 1
}

# Compare each theorem's actual `#print axioms` line against its snapshot.
# `#print axioms X` produces exactly ONE line:
#   'DLC.X' depends on axioms: [foo, bar, ...]
# Grep for that line, diff against snapshot.
MISMATCH=0
for t in "${THEOREMS[@]}"; do
  expected="$EXPECTED_DIR/$t.txt"
  # Use fgrep with the leading quote+namespace to avoid partial matches.
  # `#print axioms X` has two output forms:
  #   'DLC.X' depends on axioms: [propext, ...]           (when ≥1 axiom)
  #   'DLC.X' does not depend on any axioms                (when 0 axioms)
  # Match either by anchoring on the leading quoted name.
  # `|| true` because under `set -o pipefail` a no-match grep aborts the
  # whole script; we want to emit a MISMATCH message instead.
  actual_line=$(grep -F "'DLC.$t'" "$ACTUAL_FILE" 2>/dev/null | head -1 || true)
  if [ -z "$actual_line" ]; then
    echo "check-axioms: MISMATCH — no #print output for DLC.$t" >&2
    MISMATCH=1
    continue
  fi
  expected_line=$(sed '/^$/d' "$expected" | head -1)
  if [ "$actual_line" != "$expected_line" ]; then
    echo "check-axioms: MISMATCH on $t" >&2
    echo "  expected: $expected_line" >&2
    echo "  actual:   $actual_line" >&2
    MISMATCH=1
  fi
done

if [ "$MISMATCH" -eq 1 ]; then
  echo "" >&2
  echo "--- actual `lake env lean` stdout ---" >&2
  cat "$ACTUAL_FILE" >&2
  echo "--- end actual ---" >&2
  echo "" >&2
  echo "ERROR: axiom snapshot drift detected." >&2
  echo "If the change is intentional, regenerate via:" >&2
  echo "  cd lean && lake env lean $SCRIPT_FILE > /tmp/actual.txt" >&2
  echo "  # then update lean/expected-axioms/*.txt accordingly" >&2
  exit 1
fi

echo "check-axioms: ✓ all ${#THEOREMS[@]} snapshots match"
