#!/usr/bin/env bash
# scripts/check-axioms.sh — compare `#print axioms` output for each
# tracked theorem against `lean/expected-axioms/<theorem>.txt`.
#
# Fails on ANY difference. New axioms must be:
#   (a) intentional (docstring justifies),
#   (b) the snapshot updated in the same PR.
#
# This catches silent soundness regressions where a refactor accidentally
# introduces a new axiom dependency (e.g. a hidden `sorry`, an opaque
# definition load-bearing for a proof, or a misuse of `noncomputable def`).

set -euo pipefail

cd "$(dirname "$0")/.."

EXPECTED_DIR="lean/expected-axioms"
LEAN_DIR="lean"
SCRIPT_DIR="lean/.print-axioms"

# Each theorem is tracked as `lean/expected-axioms/<theorem>.txt`.
# The theorem's fully-qualified name is `DLC.<theorem>` (or whatever the
# snapshot's first line names).

mkdir -p "$SCRIPT_DIR"

# Generate a one-off Lean script that prints axioms for all tracked theorems.
THEOREMS=()
for f in "$EXPECTED_DIR"/*.txt; do
  [ -f "$f" ] || continue
  base="$(basename "$f" .txt)"
  THEOREMS+=("$base")
done

if [ ${#THEOREMS[@]} -eq 0 ]; then
  echo "check-axioms: no snapshots in $EXPECTED_DIR/ — nothing to check"
  exit 0
fi

# Construct a single Lean file that imports DLC and prints axioms.
SCRIPT_FILE="$SCRIPT_DIR/PrintAll.lean"
{
  echo "-- Auto-generated by scripts/check-axioms.sh — do not commit."
  echo "import DLC.Decidability"
  echo "import DLC.Correspondence"
  echo "import DLC.NonInterference"
  echo "import DLC.ObligationSoundness"
  echo "import DLC.Reduce"
  echo "import DLC.ProtocolCorrespondence"
  echo ""
  for t in "${THEOREMS[@]}"; do
    echo "#print axioms DLC.$t"
  done
} > "$SCRIPT_FILE"

# Run lake/lean and capture stdout.
ACTUAL_FILE="$SCRIPT_DIR/actual.txt"
(cd "$LEAN_DIR" && lake env lean "$SCRIPT_DIR/PrintAll.lean") > "$ACTUAL_FILE" 2>/dev/null || {
  echo "check-axioms: lake env lean failed (build broken?)" >&2
  exit 1
}

# Split actual into per-theorem chunks and compare each to its snapshot.
MISMATCH=0
for t in "${THEOREMS[@]}"; do
  expected="$EXPECTED_DIR/$t.txt"
  # `#print axioms X` produces one line per axiom set. Extract the
  # block that begins with 'DLC.$t' depends on.
  actual_chunk=$(awk -v t="DLC.$t" '
    $0 ~ "^'\''" t "'\''" { p=1 }
    p { print }
    p && NF==0 { p=0 }
  ' "$ACTUAL_FILE" | sed '/^$/d')
  if [ -z "$actual_chunk" ]; then
    echo "check-axioms: MISMATCH — no #print output for DLC.$t (theorem missing?)" >&2
    MISMATCH=1
    continue
  fi
  if ! diff -q <(echo "$actual_chunk") <(sed '/^$/d' "$expected") >/dev/null 2>&1; then
    echo "check-axioms: MISMATCH on $t" >&2
    diff <(sed '/^$/d' "$expected") <(echo "$actual_chunk") || true
    MISMATCH=1
  fi
done

if [ "$MISMATCH" -eq 1 ]; then
  echo "" >&2
  echo "ERROR: axiom snapshot drift detected." >&2
  echo "If the change is intentional, regenerate via:" >&2
  echo "  cd lean && lake env lean $SCRIPT_FILE > /tmp/actual.txt" >&2
  echo "  # then update lean/expected-axioms/*.txt accordingly" >&2
  exit 1
fi

echo "check-axioms: ✓ all ${#THEOREMS[@]} snapshots match"
