import Lake
open Lake DSL

package «dlc» where
  -- Release mode for native-decide heavy proofs (T1, T4).
  buildType := .release
  leanOptions := #[
    ⟨`autoImplicit, false⟩,
    -- Generous heartbeat budget; individual lemmas can still override.
    ⟨`maxHeartbeats, (400000 : Nat)⟩
  ]

-- Aeneas standard library. Pinned to the same commit nucleus uses so the
-- Charon-emitted .llbc files in this workspace match `nucleus`'s output.
require aeneas from git
  "https://github.com/AeneasVerif/aeneas.git" @ "b2b5e3d" / "backends" / "lean"

-- Mathlib for HeytingAlgebra, Multiset (linear context), Order theory, and the
-- categorical infrastructure used by T3 / the strong indexed monad.
require mathlib from git
  "https://github.com/leanprover-community/mathlib4.git" @ "v4.28.0-rc1"

-- Re-export the verified IFC label algebra from nucleus's portcullis-core.
-- DLC's IFC labels ARE nucleus's PermissionLattice; no fresh formalization.
--
-- Wired in at M1.Q4.a — until then `lean/PortcullisCoreImport.lean` is a
-- placeholder so the Lean build does not depend on a sibling clone of the
-- `nucleus` repository. Re-enabling this `require` is the gating change for
-- M1.Q4.a; CI's `lean.yml` job picks up the dependency automatically.
-- require portcullisCore from "../../nucleus/crates/portcullis-core/lean"

-- DLC core library — syntax, judgments, reduction, substitution.
lean_lib «DLC» where
  roots := #[
    `DLC.Syntax,
    `DLC.Judgment,
    `DLC.Principal,
    `DLC.IFCLabel,
    `DLC.Obligation,
    `DLC.Time,
    `DLC.Subst,
    `DLC.Reduce,
    `DLC.Graded
  ]

-- The four headline theorems live in dedicated libs so `lake build` can run
-- each one in parallel and the ledger.sh script can report per-theorem status.

lean_lib «Decidability» where
  roots := #[`DLC.Decidability]

lean_lib «Correspondence» where
  roots := #[`DLC.Correspondence]

lean_lib «NonInterference» where
  roots := #[`DLC.NonInterference]

lean_lib «ObligationSoundness» where
  roots := #[`DLC.ObligationSoundness]

-- §4.4 — protocol-logic correspondence theorem (Phase 2 closure).
lean_lib «ProtocolCorrespondence» where
  roots := #[`DLC.ProtocolCorrespondence]

-- Aeneas-generated translation of crates/dlc-core. Regenerated by
-- scripts/aeneas-translate.sh; non-clean diffs block merge.
lean_lib «DLCAeneas» where
  roots := #[`DLC.Aeneas.DlcCore]
  srcDir := "DLC/Aeneas"
