-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [dlc_core]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import DlcCore.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open dlc_core

/-- [core::array::{impl core::hash::Hash for [T; N]}::hash]:
    Source: '/rustc/library/core/src/array/mod.rs', lines 349:4-349:50
    Name pattern: [core::array::{core::hash::Hash<[@T; @N]>}::hash]
    Visibility: public -/
@[rust_fun "core::array::{core::hash::Hash<[@T; @N]>}::hash"]
axiom Array.Insts.CoreHashHash.hash
  {T : Type} {H : Type} {N : Std.Usize} (hashHashInst : core.hash.Hash T)
  (hashHasherInst : core.hash.Hasher H) :
  Array T N → H → Result H

/-- [core::cmp::impls::{impl core::cmp::Eq for u32}::assert_fields_are_eq]:
    Source: '/rustc/library/core/src/cmp.rs', lines 1906:12-1906:32
    Name pattern: [core::cmp::impls::{core::cmp::Eq<u32>}::assert_fields_are_eq]
    Visibility: public -/
@[rust_fun "core::cmp::impls::{core::cmp::Eq<u32>}::assert_fields_are_eq"]
axiom U32.Insts.CoreCmpEq.assert_fields_are_eq : Std.U32 → Result Unit

/-- [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field2_finish]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2473:4-2480:15
    Name pattern: [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field2_finish]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field2_finish"]
axiom core.fmt.Formatter.debug_struct_field2_finish
  :
  core.fmt.Formatter → Str → Str → Dyn (fun _dyn => core.fmt.Debug _dyn)
    → Str → Dyn (fun _dyn => core.fmt.Debug _dyn) → Result
    ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field3_finish]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2492:4-2501:15
    Name pattern: [core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field3_finish]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Formatter<'a>}::debug_struct_field3_finish"]
axiom core.fmt.Formatter.debug_struct_field3_finish
  :
  core.fmt.Formatter → Str → Str → Dyn (fun _dyn => core.fmt.Debug _dyn)
    → Str → Dyn (fun _dyn => core.fmt.Debug _dyn) → Str → Dyn (fun _dyn
    => core.fmt.Debug _dyn) → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [core::fmt::{core::fmt::Formatter<'a>}::debug_tuple_field2_finish]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2627:4-2632:15
    Name pattern: [core::fmt::{core::fmt::Formatter<'a>}::debug_tuple_field2_finish]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Formatter<'a>}::debug_tuple_field2_finish"]
axiom core.fmt.Formatter.debug_tuple_field2_finish
  :
  core.fmt.Formatter → Str → Dyn (fun _dyn => core.fmt.Debug _dyn) → Dyn
    (fun _dyn => core.fmt.Debug _dyn) → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [core::fmt::{core::fmt::Formatter<'a>}::debug_tuple_field3_finish]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 2644:4-2650:15
    Name pattern: [core::fmt::{core::fmt::Formatter<'a>}::debug_tuple_field3_finish]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Formatter<'a>}::debug_tuple_field3_finish"]
axiom core.fmt.Formatter.debug_tuple_field3_finish
  :
  core.fmt.Formatter → Str → Dyn (fun _dyn => core.fmt.Debug _dyn) → Dyn
    (fun _dyn => core.fmt.Debug _dyn) → Dyn (fun _dyn => core.fmt.Debug _dyn)
    → Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)

/-- [core::hash::impls::{impl core::hash::Hash for u8}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 812:16-812:56
    Name pattern: [core::hash::impls::{core::hash::Hash<u8>}::hash]
    Visibility: public -/
@[rust_fun "core::hash::impls::{core::hash::Hash<u8>}::hash"]
axiom U8.Insts.CoreHashHash.hash
  {H : Type} (HasherInst : core.hash.Hasher H) : Std.U8 → H → Result H

/-- [core::hash::impls::{impl core::hash::Hash for isize}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 812:16-812:56
    Name pattern: [core::hash::impls::{core::hash::Hash<isize>}::hash]
    Visibility: public -/
@[rust_fun "core::hash::impls::{core::hash::Hash<isize>}::hash"]
axiom Isize.Insts.CoreHashHash.hash
  {H : Type} (HasherInst : core.hash.Hasher H) : Std.Isize → H → Result H

/-- [core::hash::impls::{impl core::hash::Hash for u64}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 812:16-812:56
    Name pattern: [core::hash::impls::{core::hash::Hash<u64>}::hash]
    Visibility: public -/
@[rust_fun "core::hash::impls::{core::hash::Hash<u64>}::hash"]
axiom U64.Insts.CoreHashHash.hash
  {H : Type} (HasherInst : core.hash.Hasher H) : Std.U64 → H → Result H

/-- [core::iter::range::{impl core::iter::range::Step for u32}::backward_checked]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 290:16-290:74
    Name pattern: [core::iter::range::{core::iter::range::Step<u32>}::backward_checked]
    Visibility: public -/
@[rust_fun
  "core::iter::range::{core::iter::range::Step<u32>}::backward_checked"]
axiom U32.Insts.CoreIterRangeStep.backward_checked
  : Std.U32 → Std.Usize → Result (Option Std.U32)

/-- [core::iter::range::{impl core::iter::range::Step for u32}::forward_checked]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 282:16-282:73
    Name pattern: [core::iter::range::{core::iter::range::Step<u32>}::forward_checked]
    Visibility: public -/
@[rust_fun
  "core::iter::range::{core::iter::range::Step<u32>}::forward_checked"]
axiom U32.Insts.CoreIterRangeStep.forward_checked
  : Std.U32 → Std.Usize → Result (Option Std.U32)

/-- [core::iter::range::{impl core::iter::range::Step for u32}::steps_between]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 271:16-271:84
    Name pattern: [core::iter::range::{core::iter::range::Step<u32>}::steps_between]
    Visibility: public -/
@[rust_fun "core::iter::range::{core::iter::range::Step<u32>}::steps_between"]
axiom U32.Insts.CoreIterRangeStep.steps_between
  : Std.U32 → Std.U32 → Result (Std.Usize × (Option Std.Usize))

/-- [core::option::{impl core::ops::try_trait::Try for core::option::Option<T>}::branch]:
    Source: '/rustc/library/core/src/option.rs', lines 2779:4-2779:64
    Name pattern: [core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch"]
axiom core.option.Option.Insts.CoreOpsTry_traitTry.branch
  {T : Type} :
  Option T → Result (core.ops.control_flow.ControlFlow (Option
    core.convert.Infallible) T)

/-- [core::option::{impl core::ops::try_trait::FromResidual<core::option::Option<core::convert::Infallible>> for core::option::Option<T>}::from_residual]:
    Source: '/rustc/library/core/src/option.rs', lines 2793:4-2793:67
    Name pattern: [core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual"]
axiom
  core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
  (T : Type) : Option core.convert.Infallible → Result (Option T)

/-- [alloc::boxed::{impl core::cmp::PartialEq<alloc::boxed::Box<T>> for alloc::boxed::Box<T>}::ne]:
    Source: '/rustc/library/alloc/src/boxed.rs', lines 2127:4-2127:38
    Name pattern: [alloc::boxed::{core::cmp::PartialEq<Box<@T>, Box<@T>>}::ne]
    Visibility: public -/
@[rust_fun "alloc::boxed::{core::cmp::PartialEq<Box<@T>, Box<@T>>}::ne"]
axiom Box.Insts.CoreCmpPartialEqBox.ne
  {T : Type} (A : Type) (corecmpPartialEqInst : core.cmp.PartialEq T T) :
  T → T → Result Bool

/-- [alloc::boxed::{impl core::hash::Hash for alloc::boxed::Box<T>}::hash]:
    Source: '/rustc/library/alloc/src/boxed.rs', lines 2169:4-2169:44
    Name pattern: [alloc::boxed::{core::hash::Hash<Box<@T>>}::hash]
    Visibility: public -/
@[rust_fun "alloc::boxed::{core::hash::Hash<Box<@T>>}::hash"]
axiom Box.Insts.CoreHashHash.hash
  {T : Type} (A : Type) {H : Type} (corehashHashInst : core.hash.Hash T)
  (corehashHasherInst : core.hash.Hasher H) :
  T → H → Result H

/-- [alloc::boxed::{impl core::fmt::Debug for alloc::boxed::Box<T>}::fmt]:
    Source: '/rustc/library/alloc/src/boxed.rs', lines 2235:4-2235:60
    Name pattern: [alloc::boxed::{core::fmt::Debug<Box<@T>>}::fmt]
    Visibility: public -/
@[rust_fun "alloc::boxed::{core::fmt::Debug<Box<@T>>}::fmt"]
axiom Box.Insts.CoreFmtDebug.fmt
  {T : Type} (A : Type) (corefmtDebugInst : core.fmt.Debug T) :
  T → core.fmt.Formatter → Result ((core.result.Result Unit core.fmt.Error)
    × core.fmt.Formatter)

/-- [alloc::boxed::{impl core::convert::AsRef<T> for alloc::boxed::Box<T>}::as_ref]:
    Source: '/rustc/library/alloc/src/boxed.rs', lines 2352:4-2352:26
    Name pattern: [alloc::boxed::{core::convert::AsRef<Box<@T>, @T>}::as_ref]
    Visibility: public -/
@[rust_fun "alloc::boxed::{core::convert::AsRef<Box<@T>, @T>}::as_ref"]
axiom Box.Insts.CoreConvertAsRef.as_ref {T : Type} (A : Type) : T → Result T

/-- [alloc::slice::{[T]}::sort]:
    Source: '/rustc/library/alloc/src/slice.rs', lines 131:4-133:15
    Name pattern: [alloc::slice::{[@T]}::sort]
    Visibility: public -/
@[rust_fun "alloc::slice::{[@T]}::sort"]
axiom alloc.slice.Slice.sort
  {T : Type} (corecmpOrdInst : core.cmp.Ord T) : Slice T → Result (Slice T)

/-- [alloc::vec::{alloc::vec::Vec<T>}::dedup]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3701:4-3701:27
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::dedup]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::dedup"]
axiom alloc.vec.Vec.dedup
  {T : Type} (A : Type) (corecmpPartialEqInst : core.cmp.PartialEq T T) :
  alloc.vec.Vec T → Result (alloc.vec.Vec T)

/-- [alloc::vec::{impl core::hash::Hash for alloc::vec::Vec<T>}::hash]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3859:4-3859:44
    Name pattern: [alloc::vec::{core::hash::Hash<alloc::vec::Vec<@T>>}::hash]
    Visibility: public -/
@[rust_fun "alloc::vec::{core::hash::Hash<alloc::vec::Vec<@T>>}::hash"]
axiom alloc.vec.Vec.Insts.CoreHashHash.hash
  {T : Type} (A : Type) {H : Type} (corehashHashInst : core.hash.Hash T)
  (corehashHasherInst : core.hash.Hasher H) :
  alloc.vec.Vec T → H → Result H

/-- [alloc::vec::{impl core::default::Default for alloc::vec::Vec<T>}::default]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 4304:4-4304:26
    Name pattern: [alloc::vec::{core::default::Default<alloc::vec::Vec<@T>>}::default]
    Visibility: public -/
@[rust_fun
  "alloc::vec::{core::default::Default<alloc::vec::Vec<@T>>}::default"]
axiom alloc.vec.Vec.Insts.CoreDefaultDefault.default
  (T : Type) : Result (alloc.vec.Vec T)

/-- [dlc_core::time::{impl core::cmp::PartialEq<dlc_core::time::TimeBound> for dlc_core::time::TimeBound}::ne]:
    Source: 'crates/dlc-core/src/time.rs', lines 12:23-12:32
    Visibility: public -/
axiom time.TimeBound.Insts.CoreCmpPartialEqTimeBound.ne
  : time.TimeBound → time.TimeBound → Result Bool

/-- [dlc_core::principal::{impl core::cmp::PartialEq<dlc_core::principal::Principal> for dlc_core::principal::Principal}::ne]:
    Source: 'crates/dlc-core/src/principal.rs', lines 8:23-8:32
    Visibility: public -/
axiom principal.Principal.Insts.CoreCmpPartialEqPrincipal.ne
  : principal.Principal → principal.Principal → Result Bool

/-- [dlc_core::principal::{impl core::cmp::PartialEq<dlc_core::principal::PrincipalId> for dlc_core::principal::PrincipalId}::ne]:
    Source: 'crates/dlc-core/src/principal.rs', lines 25:23-25:32
    Visibility: public -/
axiom principal.PrincipalId.Insts.CoreCmpPartialEqPrincipalId.ne
  : principal.PrincipalId → principal.PrincipalId → Result Bool

/-- [dlc_core::obligation::{impl core::cmp::PartialEq<dlc_core::obligation::Obligation> for dlc_core::obligation::Obligation}::ne]:
    Source: 'crates/dlc-core/src/obligation.rs', lines 20:23-20:32
    Visibility: public -/
axiom obligation.Obligation.Insts.CoreCmpPartialEqObligation.ne
  : obligation.Obligation → obligation.Obligation → Result Bool

/-- [dlc_core::obligation::{impl core::cmp::PartialEq<dlc_core::obligation::DpBudget> for dlc_core::obligation::DpBudget}::ne]:
    Source: 'crates/dlc-core/src/obligation.rs', lines 51:29-51:38
    Visibility: public -/
axiom obligation.DpBudget.Insts.CoreCmpPartialEqDpBudget.ne
  : obligation.DpBudget → obligation.DpBudget → Result Bool

/-- [dlc_core::obligation::{impl core::cmp::PartialEq<dlc_core::obligation::ActionId> for dlc_core::obligation::ActionId}::ne]:
    Source: 'crates/dlc-core/src/obligation.rs', lines 41:23-41:32
    Visibility: public -/
axiom obligation.ActionId.Insts.CoreCmpPartialEqActionId.ne
  : obligation.ActionId → obligation.ActionId → Result Bool

/-- [dlc_core::ifc::{impl core::cmp::PartialEq<dlc_core::ifc::Label> for dlc_core::ifc::Label}::ne]:
    Source: 'crates/dlc-core/src/ifc.rs', lines 13:23-13:32
    Visibility: public -/
axiom ifc.Label.Insts.CoreCmpPartialEqLabel.ne
  : ifc.Label → ifc.Label → Result Bool

/-- [dlc_core::graded::{impl core::cmp::PartialEq<dlc_core::graded::Graded<P>> for dlc_core::graded::Graded<P>}::ne]:
    Source: 'crates/dlc-core/src/graded.rs', lines 31:23-31:32
    Visibility: public -/
axiom graded.Graded.Insts.CoreCmpPartialEqGraded.ne
  {P : Type} (corecmpPartialEqInst : core.cmp.PartialEq P P) :
  graded.Graded P → graded.Graded P → Result Bool

/-- [dlc_core::judgment::{impl core::cmp::PartialEq<dlc_core::judgment::Ctx> for dlc_core::judgment::Ctx}::ne]:
    Source: 'crates/dlc-core/src/judgment.rs', lines 15:32-15:41
    Visibility: public -/
axiom judgment.Ctx.Insts.CoreCmpPartialEqCtx.ne
  : judgment.Ctx → judgment.Ctx → Result Bool

/-- [dlc_core::syntax::{impl core::cmp::PartialEq<dlc_core::syntax::Prop> for dlc_core::syntax::Prop}::ne]:
    Source: 'crates/dlc-core/src/syntax.rs', lines 16:23-16:32
    Visibility: public -/
axiom syntax.Prop.Insts.CoreCmpPartialEqProp.ne
  : syntax.Prop → syntax.Prop → Result Bool

/-- [dlc_core::judgment::{impl core::cmp::PartialEq<dlc_core::judgment::KeyRing> for dlc_core::judgment::KeyRing}::ne]:
    Source: 'crates/dlc-core/src/judgment.rs', lines 43:32-43:41
    Visibility: public -/
axiom judgment.KeyRing.Insts.CoreCmpPartialEqKeyRing.ne
  : judgment.KeyRing → judgment.KeyRing → Result Bool

/-- [dlc_core::principal::{impl core::cmp::PartialEq<dlc_core::principal::KeyRecord> for dlc_core::principal::KeyRecord}::ne]:
    Source: 'crates/dlc-core/src/principal.rs', lines 32:23-32:32
    Visibility: public -/
axiom principal.KeyRecord.Insts.CoreCmpPartialEqKeyRecord.ne
  : principal.KeyRecord → principal.KeyRecord → Result Bool

/-- [dlc_core::judgment::{impl core::cmp::PartialEq<dlc_core::judgment::RuleName> for dlc_core::judgment::RuleName}::ne]:
    Source: 'crates/dlc-core/src/judgment.rs', lines 64:29-64:38
    Visibility: public -/
axiom judgment.RuleName.Insts.CoreCmpPartialEqRuleName.ne
  : judgment.RuleName → judgment.RuleName → Result Bool

/-- [dlc_core::obligation::{impl core::cmp::PartialEq<dlc_core::obligation::Discharged> for dlc_core::obligation::Discharged}::ne]:
    Source: 'crates/dlc-core/src/obligation.rs', lines 97:23-97:32
    Visibility: public -/
axiom obligation.Discharged.Insts.CoreCmpPartialEqDischarged.ne
  : obligation.Discharged → obligation.Discharged → Result Bool

/-- [dlc_core::obligation::{impl core::cmp::PartialEq<dlc_core::obligation::Seal> for dlc_core::obligation::Seal}::ne]:
    Source: 'crates/dlc-core/src/obligation.rs', lines 106:23-106:32
    Visibility: public -/
axiom obligation.Seal.Insts.CoreCmpPartialEqSeal.ne
  : obligation.Seal → obligation.Seal → Result Bool

/-- [dlc_core::syntax::{impl core::cmp::PartialEq<dlc_core::syntax::Term> for dlc_core::syntax::Term}::ne]:
    Source: 'crates/dlc-core/src/syntax.rs', lines 47:23-47:32
    Visibility: public -/
axiom syntax.Term.Insts.CoreCmpPartialEqTerm.ne
  : syntax.Term → syntax.Term → Result Bool

/-- [dlc_core::syntax::{impl core::cmp::PartialEq<dlc_core::syntax::Signature> for dlc_core::syntax::Signature}::ne]:
    Source: 'crates/dlc-core/src/syntax.rs', lines 126:23-126:32
    Visibility: public -/
axiom syntax.Signature.Insts.CoreCmpPartialEqSignature.ne
  : syntax.Signature → syntax.Signature → Result Bool

