-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [dlc_core]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace dlc_core

/-- [dlc_core::time::TimeBound]
    Source: 'crates/dlc-core/src/time.rs', lines 13:0-16:1
    Visibility: public -/
structure time.TimeBound where
  epoch_ms : Std.U64

/-- [dlc_core::syntax::Signature]
    Source: 'crates/dlc-core/src/syntax.rs', lines 117:0-122:1
    Visibility: public -/
structure syntax.Signature where
  alg : Std.U8
  bytes : alloc.vec.Vec Std.U8

/-- [dlc_core::principal::PrincipalId]
    Source: 'crates/dlc-core/src/principal.rs', lines 26:0-26:37
    Visibility: public -/
@[reducible]
def principal.PrincipalId := Array Std.U8 32#usize

/-- [dlc_core::principal::Principal]
    Source: 'crates/dlc-core/src/principal.rs', lines 9:0-19:1
    Visibility: public -/
@[discriminant isize]
inductive principal.Principal where
| Atom : principal.PrincipalId → principal.Principal
| And : principal.Principal → principal.Principal → principal.Principal
| Or : principal.Principal → principal.Principal → principal.Principal
| Acting : principal.Principal → principal.Principal → principal.Principal

/-- [dlc_core::obligation::DpBudget]
    Source: 'crates/dlc-core/src/obligation.rs', lines 52:0-57:1
    Visibility: public -/
structure obligation.DpBudget where
  epsilon_micros : Std.U64
  delta_micros : Std.U64

/-- [dlc_core::obligation::ActionId]
    Source: 'crates/dlc-core/src/obligation.rs', lines 42:0-42:33
    Visibility: public -/
@[reducible]
def obligation.ActionId := alloc.vec.Vec Std.U8

/-- [dlc_core::obligation::Obligation]
    Source: 'crates/dlc-core/src/obligation.rs', lines 21:0-38:1
    Visibility: public -/
@[discriminant isize]
inductive obligation.Obligation where
| Top : obligation.Obligation
| Bot : obligation.Obligation
| ActOf : principal.Principal → obligation.ActionId → obligation.Obligation
| Within : time.TimeBound → obligation.Obligation
| Tensor :
  obligation.Obligation →
  obligation.Obligation →
  obligation.Obligation
| Lolli :
  obligation.Obligation →
  obligation.Obligation →
  obligation.Obligation
| DpBudget : obligation.DpBudget → obligation.Obligation

/-- [dlc_core::ifc::Label]
    Source: 'crates/dlc-core/src/ifc.rs', lines 14:0-14:31
    Visibility: public -/
@[reducible]
def ifc.Label := alloc.vec.Vec Std.U32

/-- [dlc_core::syntax::Prop]
    Source: 'crates/dlc-core/src/syntax.rs', lines 17:0-44:1
    Visibility: public -/
@[discriminant isize]
inductive syntax.Prop where
| Top : syntax.Prop
| Bot : syntax.Prop
| Atom : Std.U32 → syntax.Prop
| Imp : syntax.Prop → syntax.Prop → syntax.Prop
| And : syntax.Prop → syntax.Prop → syntax.Prop
| Or : syntax.Prop → syntax.Prop → syntax.Prop
| Says : principal.Principal → syntax.Prop → syntax.Prop
| SpeaksFor : principal.Principal → principal.Principal → syntax.Prop
| At : syntax.Prop → ifc.Label → syntax.Prop
| Boxed : obligation.Obligation → syntax.Prop → syntax.Prop
| Within : time.TimeBound → syntax.Prop → syntax.Prop
| Tensor : syntax.Prop → syntax.Prop → syntax.Prop
| Lolli : syntax.Prop → syntax.Prop → syntax.Prop

/-- [dlc_core::syntax::Term]
    Source: 'crates/dlc-core/src/syntax.rs', lines 48:0-110:1
    Visibility: public -/
@[discriminant isize]
inductive syntax.Term where
| Var : Std.U32 → syntax.Term
| Lam : syntax.Prop → syntax.Term → syntax.Term
| App : syntax.Term → syntax.Term → syntax.Term
| Sign :
  principal.Principal →
  syntax.Term →
  syntax.Signature →
  syntax.Term
| Verify :
  principal.Principal →
  syntax.Term →
  syntax.Signature →
  syntax.Term
| Delegate : syntax.Term → syntax.Term → syntax.Term
| Attenuate : syntax.Term → syntax.Prop → syntax.Term
| Discharge : syntax.Term → syntax.Term → syntax.Term
| LiftLabel : ifc.Label → syntax.Term → syntax.Term
| Declassify : ifc.Label → syntax.Term → syntax.Term → syntax.Term
| Now : time.TimeBound → syntax.Term
| WithinIntro : time.TimeBound → syntax.Term → syntax.Term
| Pair : syntax.Term → syntax.Term → syntax.Term
| Fst : syntax.Term → syntax.Term
| Snd : syntax.Term → syntax.Term
| Inl : syntax.Prop → syntax.Term → syntax.Term
| Inr : syntax.Prop → syntax.Term → syntax.Term
| Case : syntax.Term → syntax.Term → syntax.Term → syntax.Term
| TensorIntro : syntax.Term → syntax.Term → syntax.Term
| LetTensor : syntax.Term → syntax.Term → syntax.Term
| LetSays : principal.Principal → syntax.Term → syntax.Term → syntax.Term
| SfExtract : syntax.Term → syntax.Term

/-- [dlc_core::judgment::Ctx]
    Source: 'crates/dlc-core/src/judgment.rs', lines 16:0-21:1
    Visibility: public -/
structure judgment.Ctx where
  additive : alloc.vec.Vec syntax.Prop
  linear : alloc.vec.Vec syntax.Prop

/-- [dlc_core::judgment::TypingProblem]
    Source: 'crates/dlc-core/src/judgment.rs', lines 51:0-58:1
    Visibility: public -/
structure judgment.TypingProblem where
  ctx : judgment.Ctx
  term : syntax.Term
  prop : syntax.Prop

/-- [dlc_core::graded::Graded]
    Source: 'crates/dlc-core/src/graded.rs', lines 32:0-37:1
    Visibility: public -/
structure graded.Graded (P : Type) where
  value : P
  grade : obligation.DpBudget

/-- [dlc_core::principal::KeyRecord]
    Source: 'crates/dlc-core/src/principal.rs', lines 33:0-40:1
    Visibility: public -/
structure principal.KeyRecord where
  principal : principal.PrincipalId
  alg : Std.U8
  public_key : alloc.vec.Vec Std.U8

/-- [dlc_core::judgment::KeyRing]
    Source: 'crates/dlc-core/src/judgment.rs', lines 44:0-47:1
    Visibility: public -/
structure judgment.KeyRing where
  entries : alloc.vec.Vec principal.KeyRecord

/-- [dlc_core::judgment::RuleName]
    Source: 'crates/dlc-core/src/judgment.rs', lines 65:0-128:1
    Visibility: public -/
@[discriminant isize]
inductive judgment.RuleName where
| VarA : judgment.RuleName
| VarL : judgment.RuleName
| WeakenA : judgment.RuleName
| ImpI : judgment.RuleName
| ImpE : judgment.RuleName
| AndI : judgment.RuleName
| AndEL : judgment.RuleName
| AndER : judgment.RuleName
| SaysI : judgment.RuleName
| SaysE : judgment.RuleName
| Delegate : judgment.RuleName
| Attenuate : judgment.RuleName
| Lift : judgment.RuleName
| AppIFC : judgment.RuleName
| Declassify : judgment.RuleName
| BoxI : judgment.RuleName
| Discharge : judgment.RuleName
| Now : judgment.RuleName
| WithinI : judgment.RuleName
| WithinE : judgment.RuleName
| Verify : judgment.RuleName
| OrI : judgment.RuleName
| OrE : judgment.RuleName
| TensorI : judgment.RuleName
| TensorE : judgment.RuleName
| LolliI : judgment.RuleName
| LolliE : judgment.RuleName
| LetTensor : judgment.RuleName
| SaysExtract : judgment.RuleName
| SfExtract : judgment.RuleName

/-- [dlc_core::obligation::Seal]
    Source: 'crates/dlc-core/src/obligation.rs', lines 107:0-107:12 -/
@[reducible]
def obligation.Seal := Unit

/-- [dlc_core::obligation::Discharged]
    Source: 'crates/dlc-core/src/obligation.rs', lines 98:0-104:1
    Visibility: public -/
structure obligation.Discharged where
  obligation : obligation.Obligation
  _seal : obligation.Seal

end dlc_core
